### ISSUE TITLE
issues with theme on macos

### ISSUE THREAD

**Issue by linusrg1** [Godiesc/opera-gx#1]
I think to to the nature of the placementof mac os's title bar buttons the theme has trouble functioning on macos firefox. The menu bar button is on the left of the firefox window for some reason, underlaying the buttons. Otherwise the theme looks great!

**Comment by Godiesc** [comment]
I don't have a MacOS to test the theme, so its so difficult to me fix o make compatible with that OS, Sorry, but If you manage CSS I could add your fix to the theme. 💙 And If you delete the ogx_windows-controls.css and ogx_menu.css the theme works fine?

**Comment by FormalSnake** [comment]
And the tabs get overlapped with the `ogx_menu.css` removed
<img width="137" alt="Screenshot 2022-10-11 at 14 03 35" src="https://user-images.githubusercontent.com/90651091/195098595-220d8d5e-f124-4fb0-9605-bfa47de489c4.png">

**Comment by Godiesc** [comment]
you could try adding this code to the end of userChrome.css.
```
#tabbrowser-tabs{
  padding-inline: 24px !important;
}
```
try a smaller or bigger pixels number to look it well to you.

**Comment by FormalSnake** [comment]
Thanks, i will try it.
Opera GX
<img width="1440" alt="Screenshot 2022-10-11 at 16 40 49" src="https://user-images.githubusercontent.com/90651091/195137626-ceff6e03-2083-45ea-aad4-03842af49b18.png">
Firefox GX
<img width="1440" alt="Screenshot 2022-10-11 at 16 40 59" src="https://user-images.githubusercontent.com/90651091/195137728-261d6694-4227-4cdf-b8ce-d216f5f9ea5f.png">

Maybe there is a way to move the window controls and stuff, and there is like no spacing between the window borders and the tabs, other than that it is perfect!

**Comment by Godiesc** [comment]
like I said I don´t have that OS to play with the css to make it compatible, I just can give you some code to try solve a little things, to make a space in the top add this too:
```
#TabsToolbar{
  padding-block-start: 6px !important;
}
```
And for the window controls I give up jeje, I would need that OS to test.

**Comment by FormalSnake** [comment]
> like I said I don´t have that OS to play with the css to make it compatible, I just can give you some code to try solve a little things, to make a space in the top add this too:
> 
> ```
> #TabsToolbar{
>   padding-block-start: 6px !important;
> }
> ```
> 
> And for the window controls I give up jeje, I would need that OS to test.

I might actually research that myself, might make a pull request some day, i am going to edit the config now!

**Comment by Godiesc** [comment]
that would be perfect.

**Comment by Godiesc** [comment]
you could try this code to make the window controls vertical:
```
@media (-moz-platform: macos) {:root:is([tabsintitlebar]) .titlebar-buttonbox{
    display: flex !important;
    flex-direction: column !important;
}}
```

**Comment by FormalSnake** [comment]
> you could try this code to make the window controls vertical:
> 
> ```
> @media (-moz-platform: macos) {:root:is([tabsintitlebar]) .titlebar-buttonbox{
>     display: flex !important;
>     flex-direction: column !important;
> }}
> ```

That did not work, but i can try to modify this code

**Comment by Godiesc** [comment]
do you use the developer console? In the first post of reddit/r/firefoxcss has the steps to enable. then you can select a element with the selector and see the id and classes to edit with css.

**Comment by FormalSnake** [comment]
> do you use the developer console? In the first post of reddit/r/firefoxcss has the steps to enable. then you can select a element with the selector and see the id and classes to edit with css. and if you apply only this part of the code still nothing happen?
> 
> ```
> .titlebar-buttonbox{
>     display: flex !important;
>     flex-direction: column !important;
> }
> ```

i am using the dev console, ill try just that out

**Comment by FormalSnake** [comment]
Update: if i try changing the background color, it does nothing, only in the buttonbox container

**Comment by Godiesc** [comment]
![imagen](https://user-images.githubusercontent.com/22057609/195254430-79804291-81f3-4c58-9dda-b61e9361548d.png)
 for example I used that class to edit the code I sent  you and has this change:

![imagen](https://user-images.githubusercontent.com/22057609/195254625-d5e1ab8a-4a07-48e5-b9fb-b8a009ba6a1e.png)

**Comment by FormalSnake** [comment]
On mac this doesn't work, as you can see, i added the CSS
<img width="1552" alt="Screenshot 2022-10-12 at 06 26 19" src="https://user-images.githubusercontent.com/90651091/195257354-7af5e14c-243e-4fd2-8c8b-cfadf7c44c31.png">

And this is the result:
<img width="1552" alt="Screenshot 2022-10-12 at 06 26 39" src="https://user-images.githubusercontent.com/90651091/195257466-340364a9-7cd2-4f6a-8a2c-3216dbee9c45.png">

**Comment by Godiesc** [comment]
show me how looks you selecting that window controls with the console. like this image:
![imagen](https://user-images.githubusercontent.com/22057609/195258022-0aa24ca2-f36e-4807-a32c-5bc79e6256e4.png)

**Comment by FormalSnake** [comment]
I did have to clear all my tabs in the css to be able to select it.
<img width="1440" alt="Screenshot 2022-10-12 at 06 34 58" src="https://user-images.githubusercontent.com/90651091/195258510-1d1abb18-06ad-4449-abb9-dbfd16186054.png">

**Comment by Godiesc** [comment]
if you try to give a max-width and min-width to 40px for example and a bigger height maybe could work ejje, well, it my time to sleep, maybe you could play with some rules to see if apply.

**Comment by FormalSnake** [comment]
Buenas noches

**Comment by FormalSnake** [comment]
```
.titlebar-buttonbox {
  display: flex !important;
  flex-direction: column !important;
  max-width: 40px !important;
  min-width: 40px !important;
  height: 60px !important;
  background-color: red !important;
}
```
He conseguido mover los botones, pero no se ponen en column
<img width="96" alt="Screenshot 2022-10-12 at 13 56 50" src="https://user-images.githubusercontent.com/90651091/195348421-78c39d44-f126-4b13-b220-26fc87aae070.png">

**Comment by Godiesc** [comment]
the first tab always was so near to the border of the windows?
and if you use background: red instead of background-color makes a difference?

**Comment by FormalSnake** [comment]
> the first tab always was so near to the border of the windows? and if you use background: red instead of background-color makes a difference?

I removed the padding tab rule to test out if it was conflicting in a way
and the background: red did nothing

**Comment by Godiesc** [comment]
with the developer console in the right side after selected that element are you tried to uncheck some css rule to see what happens?

**Comment by FormalSnake** [comment]
> with the developer console in the right side after selected that element are you tried to uncheck some css rule to see what happens?

¿? ¿What element? ¿And what rule?

**Comment by FormalSnake** [comment]
Yeah, maybe we should call on discord some day

**Comment by Godiesc** [comment]
I tried this code in linux and works, maybe this could work in macOS:
```
/* Linux Controls */
@media (-moz-platform: macos){ #tabbrowser-tabs{
  padding-inline-start: calc(var(--uc-vertical-toolbar-width) - 1px) !important;
    }
}
@media (-moz-platform: macos){ .titlebar-button:hover {
    appearance: none !important;
    background-color: transparent !important;
    }
}
@media (-moz-platform: macos) { .titlebar-buttonbox {
    appearance: none !important;
    position: fixed !important;
    display: flex !important;
    top: 0px !important;
    left: 0px !important;
    width: calc(var(--uc-vertical-toolbar-width) - 1px) !important;
    flex-direction: column !important;
    background: var(--lwt-frame) !important;
    direction: ltr !important;
}
}
@media (-moz-platform: macos){ .titlebar-button image{ height: 26px !important; width: 26px !important; }
    
@media (-moz-platform: macos){ .titlebar-close image { list-style-image: url("../images/closebuttonlinux.svg") !important; } }
@media (-moz-platform: macos){ .titlebar-close:hover image{ list-style-image: url("../images/closebuttonhoverlinux.svg") !important; } }
    
@media (-moz-platform: macos){ .titlebar-min image { list-style-image: url("../images/minbuttonlinux.svg") !important; } }
@media (-moz-platform: macos){ .titlebar-min:hover image{ list-style-image: url("../images/minbuttonhoverlinux.svg") !important; } }
    
@media (-moz-platform: macos){ .titlebar-max image { list-style-image: url("../images/maxbuttonlinux.svg") !important; } }
@media (-moz-platform: macos){ .titlebar-max:hover image{ list-style-image: url("../images/maxbuttonhoverlinux.svg") !important; } }
    
@media (-moz-platform: macos){ .titlebar-restore image { list-style-image: url("../images/maxbuttonlinux.svg") !important; } }
@media (-moz-platform: macos){ .titlebar-restore:hover image{ list-style-image: url("../images/maxbuttonhoverlinux.svg") !important; } }

```
![imagen](https://user-images.githubusercontent.com/22057609/195491891-0f336675-754d-4aca-b8e5-0d6472e9da47.png)

**Comment by FormalSnake** [comment]
Lo voy a intentar con una instalacion fresca, por que me sale esto:
<img width="77" alt="Screenshot 2022-10-13 at 15 21 55" src="https://user-images.githubusercontent.com/90651091/195623243-5bb42cc5-1302-4b3c-8ffa-6d254e108cf1.png">

**Comment by FormalSnake** [comment]
> /* Linux Controls */
> @media (-moz-platform: macos){ #tabbrowser-tabs{
>   padding-inline-start: calc(var(--uc-vertical-toolbar-width) - 1px) !important;
>     }
> }
> @media (-moz-platform: macos){ .titlebar-button:hover {
>     appearance: none !important;
>     background-color: transparent !important;
>     }
> }
> @media (-moz-platform: macos) { .titlebar-buttonbox {
>     appearance: none !important;
>     position: fixed !important;
>     display: flex !important;
>     top: 0px !important;
>     left: 0px !important;
>     width: calc(var(--uc-vertical-toolbar-width) - 1px) !important;
>     flex-direction: column !important;
>     background: var(--lwt-frame) !important;
>     direction: ltr !important;
> }
> }

so i just add this to the bottom of OGX_WINDOWSCONTROLS?

**Comment by FormalSnake** [comment]
and if i do that, it gets the same result sadly

**Comment by Godiesc** [comment]
try to test the last bloc of the code line to line to see what code is the one that hide the button.
```
https://github.com/media (-moz-platform: macos) { .titlebar-buttonbox {
appearance: none !important;
position: fixed !important;
display: flex !important;
top: 0px !important;
left: 0px !important;
width: calc(var(--uc-vertical-toolbar-width) - 1px) !important;
flex-direction: column !important;
background: var(--lwt-frame) !important;
direction: ltr !important;
}
}
```

**Comment by Godiesc** [comment]
sorry I pasted a code with a random link, I edited my last comment.

**Comment by FormalSnake** [comment]
same issue, i changed the linux to macos because with the linux they appeared again, but not vertical

**Comment by FormalSnake** [comment]
oh no, ill do that in a sec

**Comment by Godiesc** [comment]
if you are busy we try on other moment. :)

**Comment by FormalSnake** [comment]
sure

**Comment by FormalSnake** [comment]
i have tried it out and its this line obviously
`appearance: none !important;`

**Comment by FormalSnake** [comment]
i dont have much css experience sorry

**Comment by Godiesc** [comment]
and the rest of the code without that line do something?

**Comment by Godiesc** [comment]
and maybe it is not possible to change that icons jeje, maybe you could help me with the top padding and the left padding to the tabs-bar to the items not overflow each other..

**Comment by FormalSnake** [comment]
it does not seem possible indeed, so lets just not do overflow then

**Comment by Godiesc** [comment]
How works this:
```
@media (-moz-platform: macos){ :root[tabsintitlebar][sizemode="maximized"] #TabsToolbar{
  padding-block-start: 4px !important;
    }}
@media (-moz-platform: macos){ :root[tabsintitlebar][sizemode="maximized"] #tabbrowser-tabs{
  padding-inline-start: 24px !important;
    }}
```

**Comment by FormalSnake** [comment]
> How works this:
> 
> ```
> @media (-moz-platform: macos){ :root[tabsintitlebar][sizemode="maximized"] #TabsToolbar{
>   padding-block-start: 4px !important;
>     }}
> @media (-moz-platform: macos){ :root[tabsintitlebar][sizemode="maximized"] #tabbrowser-tabs{
>   padding-inline-start: 24px !important;
>     }}
> ```

Where do i put this?

**Comment by Godiesc** [comment]
well you can test in whatever css file of the theme, any of "ogx_...", it doesn't matter. I will put the code in a correct css only for mantain of the code, to know where is what. I only separate de code in files to a better update of the code.

**Comment by FormalSnake** [comment]
That code works! Now something you need to do is put the tab closing X in the top of the favicon, like operaGX

**Comment by Godiesc** [comment]
you could give  me a SS to see the theme in macos, I need a ScreenShot to add in my github page if you don't have a problem.

**Comment by FormalSnake** [comment]
One moment, i realised i have a bug, easy fix

**Comment by FormalSnake** [comment]
Step 1: Remove OGX_MENU.css
Step 2: Add this code where it is needed: 
```
@media (-moz-platform: macos) {#TabsToolbar{
  padding-block-start: 6px !important;
}
#tabbrowser-tabs{
  padding-inline-start: 10px !important;
}
}
```

**Comment by FormalSnake** [comment]
Here you go!
<img width="1440" alt="Screenshot 2022-10-13 at 18 16 30" src="https://user-images.githubusercontent.com/90651091/195663365-31c811b8-9ba1-4da8-9665-854e39b653fb.png">
<img width="1440" alt="Screenshot 2022-10-13 at 18 17 13" src="https://user-images.githubusercontent.com/90651091/195663406-44d6c95d-b80f-419c-9298-a1104c009247.png">

**Comment by Godiesc** [comment]
please you could update the [ogx_left-sidebar.css](https://github.com/Godiesc/opera-gx/blob/main/Extras/Left-SideBar/ogx_left-sidebar.css) with the one that I updated in the github page, I did a little update to fix the menu button when the ogx_menu.css is deleted, and after that pls give me other SS, sorry for the inconvenient.

**Comment by FormalSnake** [comment]
what did it fix? i see no difference

**Comment by Godiesc** [comment]
the hamburger menu dont show a black background by default. in your SS see that background.

**Comment by FormalSnake** [comment]
oh yes i see it now

**Comment by FormalSnake** [comment]
<img width="1440" alt="Screenshot 2022-10-13 at 18 35 34" src="https://user-images.githubusercontent.com/90651091/195666840-5144edcd-d1cc-45b3-af55-bd8d00f5baed.png">
<img width="1440" alt="Screenshot 2022-10-13 at 18 36 15" src="https://user-images.githubusercontent.com/90651091/195666864-7777e1f5-1613-46cc-a791-94de08e03f45.png">

**Comment by Godiesc** [comment]
thanks for your help, sad that the window control buttons didn't make it work jeje. I appreciate your time.

**Comment by FormalSnake** [comment]
> thanks for your help, sad that the window control buttons didn't make it work jeje. I appreciate your time.

No problem, im happy to help when you need me!

**Comment by Godiesc** [comment]
one last questions, the top padding we added is for maximized and normal windows right? you deleted that part of the code cause that only applied in maximized window?

**Comment by FormalSnake** [comment]
yeah, if i put it in fullscreen, the tabs go to the edge of the window, but it can be fixed on your end, and if i put it in maximized, in most firefox themes the padding goes away, which is also fixed here now.

**Comment by Godiesc** [comment]
> Step 1: Remove OGX_MENU.css Step 2: Add this code where it is needed:
> 
> ```
> @media (-moz-platform: macos) {#TabsToolbar{
>   padding-block-start: 6px !important;
> }
> #tabbrowser-tabs{
>   padding-inline-start: 10px !important;
> }
> }
> ```

I will add the platform: macos in the second rule, you forgote to added jeje
```
@media (-moz-platform: macos) { #TabsToolbar{
  padding-block-start: 6px !important;
}
@media (-moz-platform: macos) { #tabbrowser-tabs{
  padding-inline-start: 10px !important;
}
}
```

**Comment by FormalSnake** [comment]
lol, there is another issue, related with fonts
![Uploading Screenshot 2022-10-13 at 18.52.15.png…]()

**Comment by FormalSnake** [comment]
<img width="355" alt="Screenshot 2022-10-13 at 18 52 15" src="https://user-images.githubusercontent.com/90651091/195670079-d00d850e-a50c-43cb-bd25-328ab54ad2ca.png">

**Comment by Godiesc** [comment]
I updated ogx_contextual-menu.css , check it to update that file and make me know if that solves the problem.

**Comment by FormalSnake** [comment]
ok, ill check it out

**Comment by FormalSnake** [comment]
identical with opera GX

**Comment by Godiesc** [comment]
glad to know it. :)

**Comment by Godiesc** [comment]
to do that you can fork my repository and after that edit the file `ogx_tabs-bar.css` and add to the end of the file:
```
/* --------------------- config to MacOS ---------------------------
   ------------- partial compatibility to window Controls ----------*/
@media (-moz-platform: macos) { #TabsToolbar{
  padding-block-start: 6px !important;
}
@media (-moz-platform: macos) { #tabbrowser-tabs{
  padding-inline-start: 10px !important;
}
}
```
And after that you make a pull request, I'll accept and after that you'll see you as a contributor.

**Comment by Godiesc** [comment]
or I put your name in the MacOS section, an easy way.

**Comment by FormalSnake** [comment]
i made a pr, and maybe adding a name that links to my profile would be nice, it is the first time i contribute to a project

**Comment by FormalSnake** [comment]
Thanks a lot! I am honored

**Comment by Godiesc** [comment]
it's done now. ❤

**Comment by Godiesc** [comment]
and other thing, the close button in the favicon maybe will interfere with the sound icon button, I dont know how opera work with sound tabs.

**Comment by FormalSnake** [comment]
> and other thing, the close button in the favicon maybe will interfere with the sound icon button, I dont know how opera work with sound tabs.

I will make another issue for this
