### ISSUE TITLE
Bug in Lists

### ISSUE THREAD

**Issue by GrPK** [Godiesc/opera-gx#11]
The color of background/text is the same in a list sub-menu.

![image](https://user-images.githubusercontent.com/31523635/186525169-044a3972-fa37-419d-93c7-6e10bf1267b9.png)

**Comment by Godiesc** [comment]
hi,
The contextual menu of the theme affects the combo-box from the content of the websites, its something that happens and I don't know why, but the text should be white, I added a fix in the <code>ogx_contextual-menu.css</code> file, you could update that file with the change that I made and look if that solve the problem.
