### ISSUE TITLE
New Tab Image not showing

### ISSUE THREAD

**Issue by DJSchaffner** [Godiesc/opera-gx#12]
So I tried a few different themes of yours but none want to show the new tab page image like in the example images. I also tried using your custom main-image settings but it didn't help either.

Is there a setting I am missing?

![explorer_8ZWW1SdlVJ](https://user-images.githubusercontent.com/16212271/188240083-e92fa9ba-37a1-4c34-90a2-e0ea0840ce74.png)
![firefox_WFZXzShO1t](https://user-images.githubusercontent.com/16212271/188240374-9af4c824-cb95-490d-8dc7-4d37a7cfa079.png)

**Comment by Godiesc** [comment]
hi, I saw that none of the aspects of the theme is apply, you should copy the chrome folder and the user.js file to active the theme. you did that way?

**Comment by DJSchaffner** [comment]
I copied those to my active firefox profile yes. Or do I have them in the wrong location?
![explorer_y8OnpysKEh](https://user-images.githubusercontent.com/16212271/188262734-d015dae4-96db-4671-b48d-4393ef495289.png)

**Comment by DJSchaffner** [comment]
Ok, turns out i put them in the %AppData%/Local folder but the should have been in %AppData%/Roaming. It works now!

**Comment by Godiesc** [comment]
I'm glad that you could solve it. :)
