### ISSUE TITLE
themes 

### ISSUE THREAD

**Issue by ASRS-00** [Godiesc/opera-gx#13]
Themes in images folder of chrome/ newtab wont upload. 
I have tried to play wit it not sure why its happening 
![themes 2](https://user-images.githubusercontent.com/113309203/189545674-bcad1e6b-0de8-4d52-9dc3-33fdd1cfb410.png)
![themes 3](https://user-images.githubusercontent.com/113309203/189545677-0df554f0-2395-4fcb-a89f-c8a94332fe58.png)
![themes](https://user-images.githubusercontent.com/113309203/189545678-a349626a-2041-4636-be0f-d146d9f77b5f.png)

**Comment by Godiesc** [comment]
hi
I can see in the image of the code that you share that you don't put the extension of the image, for example if the image is a jpg
you should put: wallpaper.jpg    , if the image is png like to the default you should keep the extension: wallpaper1.png   , etc.

**Comment by ASRS-00** [comment]
let me try that!

**Comment by ASRS-00** [comment]
Its the same issue, im able to change the color but not the main img



![themes 5](https://user-images.githubusercontent.com/113309203/189546502-ddbb8f5f-b217-4d75-bb77-37724da64f86.png)
![themes 4](https://user-images.githubusercontent.com/113309203/189546505-41787e68-504b-46d4-a6c0-3566b3bd9651.png)

**Comment by Godiesc** [comment]
not that way, look for a tutorial to show the extensions of files and its going to be easy, for example in [this video](https://www.youtube.com/watch?v=8mutk0fH81s), and all the images will have its own extensions, after that you need to copy that name and use it in the code, I saw in your image that you changed the name of the images but I mean that you need to change the name in the code.

**Comment by ASRS-00** [comment]
... xD im so sorry i dont know what else to do.
![themes 8](https://user-images.githubusercontent.com/113309203/189547145-86e414cd-e880-42c5-8155-89d26b961fce.png)
![themes 7](https://user-images.githubusercontent.com/113309203/189547149-b233ccd9-2893-4366-9ab3-a4a70e25495a.png)
![Themes 6](https://user-images.githubusercontent.com/113309203/189547152-5bbfa0e4-bd1e-4d8a-b46b-a78891ca3551.png)

**Comment by ASRS-00** [comment]
i even tried to plug in the full path ( copy as path option)

**Comment by Godiesc** [comment]
when you install the theme with the original files you see the dafault image or not?

**Comment by ASRS-00** [comment]
no! i didn't actually

**Comment by Godiesc** [comment]
I don't have macOS to test the theme but the path should select the image of that folder by default, I don't know what could be the problem, sorry.

**Comment by ASRS-00** [comment]
no worries !
i have windows

**Comment by Godiesc** [comment]
windows 11? should be complete compatible. it's estrange.

**Comment by ASRS-00** [comment]
si no se porque esta fregado XD tines discord?

**Comment by Godiesc** [comment]
I see that the first / in the path isnt correct, you changed it?

**Comment by ASRS-00** [comment]
let me see

**Comment by Godiesc** [comment]
Enviaste el reporte en ingles y pues pensé que hablaba ingles jaja

**Comment by Godiesc** [comment]
bueno todos los / deben ser este /, pero los tienes del otro lado \ , será ese el problema.

**Comment by ASRS-00** [comment]
jaja weyyyyyy soy menso ... eria/// y le puse / \ \

**Comment by ASRS-00** [comment]
si :) voy ir a llorar . gracias

**Comment by Godiesc** [comment]
entonces ya está funcionando bien el tema? para cerrarlo?
