### ISSUE TITLE
Menu says Menú

### ISSUE THREAD

**Issue by Moosyu** [Godiesc/opera-gx#14]
Don't know if this is on purpose but you can change it by editing menu-label in ogx_root-personal.css

**Comment by Godiesc** [comment]
It's not a issue, my browser language is Spanish and for that the label menu is menú. I created the file you mentioned to people could custom the theme in a easy way.

**Comment by Moosyu** [comment]
Oh, Sorry about the mistake

**Comment by Godiesc** [comment]
no problem. I appreciate you comment and I'm glad can help you.
