### ISSUE TITLE
Different font when hovering over things

### ISSUE THREAD

**Issue by Moosyu** [Godiesc/opera-gx#15]
Sorry for making issues in such quick succession but I have a problem which seems unable to fix with your guide. When hovering over things like bookmarks and tabs it turns the font to what I believe is the default in HTML. Here is an example:
Before using opera gx theme
![Capture](https://user-images.githubusercontent.com/70246651/192447900-91a50e14-e024-4672-bf1e-bb867bd84072.PNG)
After using opera gx theme
![Capture PNG(2)](https://user-images.githubusercontent.com/70246651/192447904-38af7453-0ac5-4e9f-a6db-d7db4274c765.PNG)

**Comment by Godiesc** [comment]
hi, 
well I tried to make all the >hover< the same but was impossible jajaja, but I let it that way, maybe I should remove that changes by default, you could delete the lines 95-106 form chrome>components>ogx_contextual-menu.css file to solve it.

**Comment by Moosyu** [comment]
Thanks that worked!

**Comment by jwlkns** [comment]
Alternatively, you could also download the [Fira Sans font from Google](https://fonts.google.com/specimen/Fira+Sans). It's not a standard windows font, so it defaults to something else if it cannot find the specified font in the css file.
