### ISSUE TITLE
Opera Gx Sidebar

### ISSUE THREAD

**Issue by Tyrichyrich** [Godiesc/opera-gx#16]
Hello. I just wanted to say that if the Opera Gx Sidebar was added I would switch over to Firefox faster than you could say update. It's the own thing that makes just stay with Opera Gx for the time being, but with manifest v3 and google I wanted to switch to Firefox faster than ever. Please don't rush to fill my request but it would be nice.

**Comment by Godiesc** [comment]
hi,
Do you mean the sidebar with the social media access? I think it could be possible with an extension, I can't create new elements, the theme is created just playing with css rules.

**Comment by Tyrichyrich** [comment]
Sorry for not responding and I've tried looking for extensions but none of them seem to work. Yes, it is the social media button sidebar.

**Comment by Tyrichyrich** [comment]
On second glance it might actually exist, thx for making this skin exist.
