### ISSUE TITLE
Does it use more resources?

### ISSUE THREAD

**Issue by arghanath007** [Godiesc/opera-gx#17]
> Does it take more resources to run like when themes are applied to an OS, it uses a bit more resources. So it will use a bit more resources or not? Just curious before I try it.

**Comment by Godiesc** [comment]
hi,
in every start of the browser the files of the theme will be added to the css of the browser and could affect just a little bit the start time.

**Comment by arghanath007** [comment]
Thanks for the reply. I will try it on my Ubuntu system and let you know if it works on it or now. It will mostly likely as it worked on Marjaro Linux.
