### ISSUE TITLE
Make light theme

### ISSUE THREAD

**Issue by xmha97** [Godiesc/opera-gx#18]
# Light
![GX Classic 1 (Light)](https://user-images.githubusercontent.com/23485114/194703172-15e76ec9-0912-4cdb-9274-cfc79fa18e99.png)

# Dark
![GX Classic 1 (Dark)](https://user-images.githubusercontent.com/23485114/194703160-9d7a226d-16c7-40cd-943c-9f7a1dfc2858.png)

**Comment by Godiesc** [comment]
hi,
I don't use light themes and don't know how difficult could be adapt this theme to make it compatible.

**Comment by FormalSnake** [comment]
> hi, I don't use light themes and don't know how difficult could be adapt this theme to make it compatible.

you could check if system is in dark mode using CSS, or maybe detect if the theme wants to use a lighter color.

**Comment by Godiesc** [comment]
I updated the theme to make it compatible with white themes, make me know any bug, thanks.
