### ISSUE TITLE
Botón de menú sobrepuesto en la barra de URL.

### ISSUE THREAD

**Issue by kaos-55** [Godiesc/opera-gx#2]
Hola, primero que nada excelente tema para Firefox. Hay un pequeño problema con el tema GX, cuando se abre una ventana popup se muestra el botón de menú y este sobrepone en la barra de URL. Idealmente en este tipo de ventanas no debería aparecer el botón de menú, adjunto imagen del problema.
![gx_fx](https://user-images.githubusercontent.com/86812371/153987424-f67d17e1-52a9-46a8-b0ce-7e6d8445bd06.png)

**Comment by Godiesc** [comment]
Gracias por reportar el problema, no acostumbro a ver ventanas de popup por lo que no me había percatado de eso, espero resolverlo pronto. 💙

**Comment by Godiesc** [comment]
The bug has fix now, thank for reporting. 💙 ✌peace and love.

**Comment by Godiesc** [comment]
The bug has fix now, thank for reporting. 💙 ✌peace and love.
