### ISSUE TITLE
Move close tab to favicon, like opera GX

### ISSUE THREAD

**Issue by FormalSnake** [Godiesc/opera-gx#23]
https://user-images.githubusercontent.com/90651091/195704159-9629ae04-9c98-41a7-9024-64ef1e78a088.mov

This is how it would work with audio tabs

**Comment by Godiesc** [comment]
hi, you need to show me the event :hover on that elements to give a right style to that buttons jeje, put the mouse over them to show me what happens.

**Comment by FormalSnake** [comment]
https://user-images.githubusercontent.com/90651091/195774550-02ce2339-9747-4572-9d79-44a2ed890555.mov

**Comment by FormalSnake** [comment]
that is what happens

**Comment by Godiesc** [comment]
I updated the files: ogx_close-button.css and ogx_sound.css to make that changes, I change the color of muted icon to white to make a difference from sound tab.

**Comment by FormalSnake** [comment]
Alright, ill check it out

**Comment by FormalSnake** [comment]
It works perfectly! Although one last change that you need to make is that the close button appears when you hover on the tab, not the icon.

**Comment by Godiesc** [comment]
when a tab is charging and you put the mouse over it the animation disappear and the X button appear?

**Comment by FormalSnake** [comment]
The animation disappears.
https://user-images.githubusercontent.com/90651091/195910965-d8ca0df1-f390-4598-881a-723468aeb017.mov

**Comment by Godiesc** [comment]
I updated the file ogx_close-button.css.

**Comment by FormalSnake** [comment]
Its perfect!
