### ISSUE TITLE
How to change text of menu component?

### ISSUE THREAD

**Issue by JaydenDev** [Godiesc/opera-gx#27]
So there is the Menu button
![image](https://user-images.githubusercontent.com/92550746/196038471-38d13bc3-7e82-4fdd-bd93-75d2aa64ece2.png)
It's in spanish, is there anyway I can change the u to be an english u?

**Comment by Godiesc** [comment]
hi, maybe you didn't download the latest version of the theme (Green button->download Zip), by default is in English now, the file chrome->components->ogx_root-personal.css the line 25 has the text to that button.

**Comment by JaydenDev** [comment]
> hi, maybe you didn't download the latest version of the theme (Green button->download Zip), by default is in English now, the file chrome->components->ogx_root-personal.css the line 25 has the text to that button.

Ok, usually id the latest release in the releases tab to be the latest version, thanks!

**Comment by Godiesc** [comment]
I understand, I make a release version not often cause I update the theme many times before or after the release version of the browser, in this days I updated the theme so many times but I'm near to update the next release, maybe you should go back in the next days to take the next version.
