### ISSUE TITLE
[Bug?] Sidebar shows while window is fullscreened

### ISSUE THREAD

**Issue by Henry-Hiles** [Godiesc/opera-gx#28]
Hey there! This theme is great, keep it up! My one complaint is that the sidebar stays when a website is fullscreened, but only the firefox logo on it, the others dissapear. Can provide screenshot if neccicary. Thanks for reading :)

**Comment by Godiesc** [comment]
hi, I updated the file to solve that problem. You can check it.

**Comment by Henry-Hiles** [comment]
Thanks! That fixed it!
