### ISSUE TITLE
Extensions space issues in Oneline 

### ISSUE THREAD

**Issue by kotobuki09** [Godiesc/opera-gx#29]
https://i.imgur.com/XZXj5eq.png

I having some weird issues with the latest version of opera-gx on Firefox 106.0 (64-bit)
The place suppose to be where all the extensions stay is just black space then the whole extension is moved to the right side.
Can you check on this issue?

**Comment by Godiesc** [comment]
hi, with the "customize toolbar" option you need to move that icons next to your account icon. This version of one-line was designed to put the icons on the right side. Maybe that space you mentioned is a flex space that need to be deleted with the customize toolbar option.

**Comment by kotobuki09** [comment]
Thank you for that. It's got fixed when I move all the extenstion to the right side!
