### ISSUE TITLE
New-Tab search bar not visible

### ISSUE THREAD

**Issue by AzureB1te** [Godiesc/opera-gx#3]
The big search bar on the new tab page/homepage isn't visible. Using Firefox (with arkenfox arkenfox) 97.0.1

**Comment by Godiesc** [comment]
Hi, That search bar isn't necessary right now cause if you write on it it links you to the awesome bar, but if you want the searchbar you need to delete or comment ( /* ... */ ) the line 208 from the file: ogx_userContent-personal.css inside "components" folder. Make me know if that solve your problem. 💙
