### ISSUE TITLE
Missing separators in left sidebar

### ISSUE THREAD

**Issue by ZombiePippin** [Godiesc/opera-gx#30]
How can I add the app button separators on left sidebar. I seem to be missing them in customize toolbar.

**Comment by Godiesc** [comment]
hi, if you are using just bookmarks in the left sidebar: right click-> add separator.
If you are using for extensions like in the preview of this theme you will need to add code. can you tell me exactly what you want and if you take a screenshot could be more helpful.

**Comment by ZombiePippin** [comment]
That fixed it. Thanks for the quick reply. Your theme is perfect.

**Comment by Godiesc** [comment]
I'm glad all works fine to you. ❤
