### ISSUE TITLE
Problem with the context menu

### ISSUE THREAD

**Issue by Car0lina5** [Godiesc/opera-gx#32]
I apologize in advance because I have no idea how to use this here. I usually just download stuff from github and use it, creating an account here just because I don't know what else to do or search.

So, I have a problem with the context menu and I have no idea how to solve this... I have tested it in firefox and librewolf, both have the same problem. I tested some other themes and the context menu worked. I also tried the "Chameleons-Beauty" theme and it presents the same problem for me.

I found a similar problem to mine here: https://www.reddit.com/r/FirefoxCSS/comments/xhevzf/how_to_remove_leptons_context_menu_border/
I tried to fix it by myself but I have no idea how to fix it because in my browser the style is completely different... I hope you can help me. Thanks.

I am using windows 11, in case it helps. 
![04 11 2022  -  14 14  -  ](https://user-images.githubusercontent.com/117472773/200035932-69adfb4a-6293-42eb-9ced-d380a847cfa8.png)

**Comment by Godiesc** [comment]
hi, thanks for your report,
unfortunately I don't have windows 11 to test the theme, I assume the theme works fine in windows 11 cause is similar to windows 10, but it seems to not all works fine.
The fist thing that you can test i if you delete the lines 49-64 form chrome>>components>>ogx_contextual-menu.css file. this could solve the color to the top icons background.

**Comment by Car0lina5** [comment]
I took the "ogx_contextual-menu.css" again from the zip and it looks like this. If I delete lines 49 and 64 it looks like my print above (sorry, I think I got the prints mixed up). Anyway, it still has this border on the side. I can't seem to get it to look like yours at all and apparently other themes can't change this part either. Is there something I need to activate so that the style is applied to the context menu as well? I'll leave the link to your screenshots that I saw and on mine unfortunately nothing looks the same :(((( 
I've been trying to fix it since yesterday and I don't know what it is anymore :((((
Prints: https://user-images.githubusercontent.com/22057609/186518856-2a474e30-40fa-4af0-a8df-02d27d00403b.png
https://user-images.githubusercontent.com/22057609/162596748-d92f0dab-c635-40f6-b216-48ce7a39cd64.png

![image](https://user-images.githubusercontent.com/117472773/200041185-14f843d3-5744-4271-ae00-da421fa8c981.png)

**Comment by Godiesc** [comment]
the first link you send is how looks now the theme, the second link is an old screenshot, I don't know where that image comes from jeje, but the contextual menu for sure is affected for windows 11, Microsoft update that OS so frequently and maybe has a lot of changes every time. Maybe I'll install windows 11  in virtual box or something  like that to test it. or maybe you trust in me and give me the opportunity to go into your machine with [TeamViewer](https://www.teamviewer.com/es/). jeje

**Comment by Car0lina5** [comment]
Unfortunately it didn't work, if you can help me with that or even install it for me (maybe I'm doing something right) I will be eternally grateful.
That's fine with me. Where can I give you access to the team viewer? Is there another way I can talk to you? The main problem here is that I am Brazilian and I don't write very well in English, I use translator to make it easier D:

**Comment by Godiesc** [comment]
I speak spanish jeje, I do not know how to speak Portuguese jeje, but let me start my pc and with team viewer you give me the code that the program give you and that make me connect to your pc and can test the theme, if you have time.

**Comment by Car0lina5** [comment]
I'm sorry, I forgot the most obvious thing. My custom windows theme is conflicting. If I use the original theme everything works perfectly. I'll need to fix this or stop with the custom windows themes. Last question... do you know of something that can make the windows theme not to conflict with the browser? If you don't know it, that's fine. Thank you very much for taking the time to help me. I'm 2 days trying to find out what it could be. You are amazing, thank you!

![image](https://user-images.githubusercontent.com/117472773/200047408-5edd4032-97aa-4dbe-9a82-fe57187a5bcb.png)

**Comment by Godiesc** [comment]
it seems like that custom windows themes always affects all this kind of themes (CSS), I dont use them so I don't know what can be the problem, if you want to keep using them o you need to solve that kind of issue with the developer console if you know CSS jeje

**Comment by Car0lina5** [comment]
I don't know anything but I will learn hahaha
Thanks a lot for the help! <3

**Comment by Godiesc** [comment]
you're welcome.
