### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by Henry-Hiles** [Godiesc/opera-gx#34]
Hey there! This is probably a very stupid question, but would it be possible for me to install this on android? I am using the Iceraven browser, though i am open to using any firefox-based browser. I do have root access, and I have seen other projects which change user.js, e.g. https://github.com/pyllyukko/user.js#single-profile-installation, but i was wondering if it would be possible to do something like that with this theme? Thanks for your time.

**Comment by Godiesc** [comment]
Hi, this theme is for desktop version and don't work on other versions. For android I never tried any theme or even I don't know if it's possible to do that.

**Comment by Henry-Hiles** [comment]
Thx, thats what i thought, thx for your tkme :)
