### ISSUE TITLE
Firefox Nightly left side bar bug

### ISSUE THREAD

**Issue by rafaelrocha26** [Godiesc/opera-gx#35]
Hi, first let me say that your theme is awesome. Second, when I use Firefox Nightly with the left side bar there is a small portion of it in the bottom that is empty, it's like the bar was cut in that part. I don't know much about coding so maybe I'm doing something wrong, but I don't have this problem with standard Firefox. Thanks for the attention.

**Comment by Godiesc** [comment]
hi,
the nightly version is unstable so my theme has a lot of problems in that version, but to solve the problem you mentioned you need to replace the line 23 from the ogx_left-sidebar.css file with this:
`padding-top: calc(var(--toolbar-height-personal) + 14px) !important;`

**Comment by rafaelrocha26** [comment]
Many thanks, it worked. But Nightly is quite unstable Indeed. I think I will just use Developer edition or just standard Firefox.
