### ISSUE TITLE
Please bring back the Firefox word and the logo in the midle

### ISSUE THREAD

**Issue by SonPro1102** [Godiesc/opera-gx#37]
Like this
![image](https://user-images.githubusercontent.com/119962558/205984991-089cdcc9-f648-4187-a458-6373eaf49868.png)
Also can u remove the search bar while u r at it, theres already a searchbar ontop

**Comment by Godiesc** [comment]
hi,
The logo, wordmark and search bar, in the new tab page, you will always be capable to hide or show with the options in the [ogx_root-personal.css](https://github.com/Godiesc/opera-gx/blob/main/chrome/components/ogx_root-personal.css) file.
the lines 39-40 has the code for that. Make me know if you need more help.

**Comment by SonPro1102** [comment]
Tks m8, it worked
