### ISSUE TITLE
Customize <select> element item height?

### ISSUE THREAD

**Issue by initialsDNA** [Godiesc/opera-gx#38]
I have been combing through the .css files in `chrome > components` but could not find an entry allowing me to adjust the style for <select> elements. Where are these handled?

**Comment by Godiesc** [comment]
hi,
What element you want to change its height? A screenshot will be useful. the <code>ogx_root-personal.css</code> file has some usual and useful variables to change, did you try that?

**Comment by initialsDNA** [comment]
Using w3schools code as an example, I wanted to change the height of each item in a dropdown box. So the "Volvo", "Saab", "Mercedes", and "Audi" elements. 

![image](https://user-images.githubusercontent.com/9056746/211166845-55618ff4-1907-40cb-a3ad-8e3ddedaeda0.png)

**Comment by Godiesc** [comment]
mm, well Firefox treat that like a contextual menu, in my this theme (Firefox-GX) in the <code>ogx_contextual-menu.css</code> file, the line 6 has code to change th height of the button, but not the height of the font.

`    padding-block: 15px !important; `

**Comment by initialsDNA** [comment]
Sorry for the delay, was a busy weekend. Thanks, that was exactly what I needed to change to get thinks looking the way I wanted!
