### ISSUE TITLE
New tab buttom looking squished.

### ISSUE THREAD

**Issue by SquashedBoi** [Godiesc/opera-gx#39]
The + sign for my new tab button appears to be squished. I am running a 21:9 monitor, might be the cause? Please let me know if there is any way to adjust its boundaries. Thanks.

![Screenshot 2023-01-08 190823](https://user-images.githubusercontent.com/71244205/211192788-e0875b86-35b4-4cbf-9a8a-6c44b3f7e58a.png)

**Comment by Godiesc** [comment]
hi, 
be sure to all the rules of user.js are apply in about:config

**Comment by SquashedBoi** [comment]
Hi,
that did the trick. thank you very much. Great theme :).
