### ISSUE TITLE
NTP Wallpaper doesn't change with theme changes

### ISSUE THREAD

**Issue by AzureB1te** [Godiesc/opera-gx#4]
The "stock" wallpaper is locked to the default fuschia color scheme. Changing themes through the themes engine, or editing the CSS doesn't help.

**Comment by Godiesc** [comment]
Hi, you have 2 ways to change the wallpaper.
The first one is change the name of the "wallpaper" you want and set it "wallpaper" on its name (you could rename the actual wallpaper and make it other name like: Oldwallpaper), and the theme will display the image with the name: "wallpaper", on the "images" -> "newtab" folder, it is the easy way to change the wallpaper. A restart of the browser is necessary. 
 https://imgur.com/a/Bp3mYXh
The second way is editing the ogx_userContent-personal.css file, the line 302, you will see that is the direction to the image, you could write the name of the image if you put you own, but changing like this: background: url("../images/newtab/wallpaper2.png") display the wallpaper 2. A restart of the browser is necessary. 
https://imgur.com/a/gHlrvBg
