### ISSUE TITLE
Problem with Contextual Menu Colours

### ISSUE THREAD

**Issue by GrPK** [Godiesc/opera-gx#5]
Hello There! First of all, I will specify that I use a custom windows theme and this is the main cause that lead to this issue.

However, I'm asking for help because I think this problem can be fixed with a little help regarding understanding contextual-menu.css

This is how my contextual menu looks right now 
![image](https://user-images.githubusercontent.com/31523635/162576832-4d1c5493-085f-4de3-b906-a651c0d8b570.png)

What changes I have do to in order to make it look like the original gx menu or maybe something similar to it. (I also had a problem with windows buttons, but I fixed it using one of firefox-csshacks css)

Thanks for your help!

**Comment by GrPK** [comment]
![Also added a photo of hovering over a menu](https://user-images.githubusercontent.com/31523635/162577401-092a3ad8-ac26-4c3a-a8f7-a342a6b8e00b.png)

**Comment by Godiesc** [comment]
hello there,
1.- A custom theme means that you have a complete theme to windows made it from a non-windows developer?
2.- I'm glad you fix the windows buttons issue that you had.
3.- The theme is for dark windows themes, maybe you have set a light theme and that cause the white top bar of the contextual menu, I don´t know how works other themes than the default themes from windows.
4.- To set other values to test it I could give you a steps to do to prove if it works because I don't have a windows custom theme to test it by my own.

**Comment by GrPK** [comment]
1. Yes, theme is https://www.deviantart.com/niivu/art/Paranoid-Android-Windows-10-Themes-821696974
3. I checked, everything is set to dark on windows
4. I'm glad to test everything, I've made some alternative context menu using as template this https://www.reddit.com/r/FirefoxCSS/comments/7vaucv/windows_10_context_menus/ and it kinda looks the same, but if you can show me how to change in your css, I'm more than happy

Here is my workaround
[ogx_contextual-menu1.zip](https://github.com/Godiesc/opera-gx/files/8457295/ogx_contextual-menu1.zip)

**Comment by Godiesc** [comment]
1.- To fix the windows buttons I hope you just deleted the <code>ogx_windows-controls.css</code> to conserve the buttons of you custom theme without modifications. 
2.- You could try copy and paste the code from [here](https://pastebin.com/EcGFMYez) to the <code>ogx_contextual-menu.css</code> file, I added and edited some lines to solve the problems I identified in the imeges you share, but you need to write me the problems you present too. And how I didn't have where to test it is difficult for me.

**Comment by GrPK** [comment]
Tested, the head of contextual menu is fixed, but the margin and the black text remains 
![image](https://user-images.githubusercontent.com/31523635/162582663-ad326e6b-28ad-4984-9e9d-a7aa2944f321.png)


For 1. Nope,I just added a file from csshacks
[window_control_fallback_for_custom_windows_theme.zip](https://github.com/Godiesc/opera-gx/files/8457345/window_control_fallback_for_custom_windows_theme.zip)

Also, if it is easier for u, we can use another platform of your choice for direct debugging (like discord or skype)

**Comment by Godiesc** [comment]
![imagen](https://user-images.githubusercontent.com/22057609/162583137-7c3faad0-3d12-4c2d-88c1-afc41a8a96a5.png)

We could use the fast assistance from windows accessories.

**Comment by GrPK** [comment]
After some debugging and changing the theme, I made the context menu work out of the box.

However, I saw that you pushed a new update. Can u bring back the separator line and make it red, like you did in "Menu" tab? I think it would look awesome and keep unity in theme

**Comment by Godiesc** [comment]
![imagen](https://user-images.githubusercontent.com/22057609/162596748-d92f0dab-c635-40f6-b216-48ce7a39cd64.png)

Right now the theme looks like this, maybe with your personalize OS theme there are so many difference from the original view for the default OS theme. The Theme is based on the Opera and I tried to keep the color of that browser theme, but I could edit the background color of the contextual menu more darker in a near future.
