### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by daniloogoncalves** [Godiesc/opera-gx#6]
Hi there,
How can I change the order of these button. It is more intuitive for the back button to be left.

![Screenshot 000315](https://user-images.githubusercontent.com/72620526/166994637-e74c9dff-8e24-4bce-aaf1-4fc526e9fd2f.png)

And is it possible to remove the menu button with the firefox logo?

![Screenshot 000316](https://user-images.githubusercontent.com/72620526/166995187-2fc3fa6b-4e71-4dc3-b489-7417ee2b9be0.png)

And is it possible to displace this "more tools ..." button to the right of the toolbar?

![Screenshot 000317](https://user-images.githubusercontent.com/72620526/166995431-f642b9f9-489a-4772-b632-795fd2b26c38.png)

Thanks in adv.

Best

**Comment by Godiesc** [comment]
hi,
1.- The first issue you mention isnt part of the theme, so, you need to: right clic >personalize toolbar, and move that icons in the right way.
2.- you mean delete de firefox (keep the 3 horizontal lines) image or delete the button to it doesnt appear?
3.- Are you using the oneline config? I didnt try to move the buttons to the right, maybe in a future update I do that (I dont know how to do that).

**Comment by Godiesc** [comment]
hi there, 
I updated the theme with a second oneline config to do the enhancement posted in this report.it works well in windows and other OS that have the window controls on the right side.
