### ISSUE TITLE
Tabs cut off

### ISSUE THREAD

**Issue by zurahk** [Godiesc/opera-gx#7]
The Top tab seems to be cut off only in windowed mode. Is there a fix or way around this other than using full screen all the time?

Otherwise, great theme, absolutely love it.
![Untitled](https://user-images.githubusercontent.com/6202392/167316283-fc05b915-ed57-4990-86ea-d12ef2ceac55.png)

**Comment by zurahk** [comment]
Line 16, in the ogx_tabs-bar 
.tabbrowser-tab .tab-content {margin-top: calc(var(--margin-top) **+ 1px)** after changing it to 2px this is the result. Windowed looks fine but then fullscreen the top looks clearly thicker now. So no clue. 
![tabs](https://user-images.githubusercontent.com/6202392/167317131-07782967-6147-443a-9b62-538a717bcca4.png)

**Comment by Godiesc** [comment]
hi, 
Which version of OS are you using, in git-hub page there is a Compatibility section but maybe your OS wasn't tested. But you could change the line 52 in the ogx_root.css, change 1px or 2px, but it will be necessary other change to align the menu button.

**Comment by zurahk** [comment]
Windows 11, ill give those changes a try that you mentioned

**Comment by zurahk** [comment]
Thea

> hi, Which version of OS are you using, in git-hub page there is a Compatibility section but maybe your OS wasn't tested. But you could change the line **52 in the ogx_root.css, change 1px or 2px**, but it will be necessary other change to align the menu button.

this actually worked perfectly. the alignment doesnt SEEM or appear too to be off with anything else but that did seem to work.

**Comment by Godiesc** [comment]
I mean the menu button "opened", maybe could appear a bad align.

**Comment by zurahk** [comment]
> I mean the menu button "opened", maybe could appear a bad align.
ahh yeah, i see what your talking about

**Comment by Godiesc** [comment]
in the ogx_menu.css the line 80 has the number to fix that, if you add 1px before you need to add a number here, for example change to: -30px.

**Comment by zurahk** [comment]
So after making those two changes you mentioned i.e ogx_menu.css -30 and  ogx_root.css, change 1px  and reverting the changes i made from the -2 to -1 in ogx_tabs-bar 

Everything appears to line up and over the last few days i havent notice anything off. Overall Id say its good and Works on Windows 11. 
![image](https://user-images.githubusercontent.com/6202392/168166690-b9f232c7-ff0e-4107-95f0-2910f1c3c6fb.png)
![Tabs](https://user-images.githubusercontent.com/6202392/168167125-ffe36419-efeb-4c03-bd17-7db7fc4e23f0.png)

**Comment by Godiesc** [comment]
I'm glad it works for you, thanks for reporting the issue. 💙

**Comment by zurahk** [comment]
No problem! Anytime :)
