### ISSUE TITLE
"Save Link As" is highlighted by default

### ISSUE THREAD

**Issue by sorat0mo** [Godiesc/opera-gx#9]
Issue is same as title
![20220707_00004](https://user-images.githubusercontent.com/11853019/177791364-aa89268a-28b4-437a-a05c-1e65905e928d.jpg)

[Peek 2022-07-07 21-57.webm](https://user-images.githubusercontent.com/11853019/177791532-801df5bb-1f1a-4524-883e-d97e020cdce4.webm)

Is there a setting I can change?

**Comment by sorat0mo** [comment]
Thanks for your reply, but this did not fix the problem. I am using firedragon from chaotic-aur. I will test this on other forks.

**Comment by Godiesc** [comment]
hi again,
I dont have any problem, sad that the theme doesn't work well for you.

![imagen](https://user-images.githubusercontent.com/22057609/177828337-57cc69b0-97a3-4419-bef0-d3ab328fe544.png)

**Comment by sorat0mo** [comment]
![20220708_00001](https://user-images.githubusercontent.com/11853019/177839568-2cda539f-3df5-47fd-b347-3f7399eac6e1.jpg)

I tried editing the new lines

`@media (-moz-platform: linux) {.menu-right {`

and change `.menu-right` to `#context-savelink`, it seems the color became dimmer. So there is another config being applied on it apparently

**Comment by Godiesc** [comment]
it appears that that item the theme take like is a selected item, and the lines for that are [this](https://github.com/Godiesc/opera-gx/blob/9030aa050309e2c8460224455a5a703605fc103b/chrome/components/ogx_contextual-menu.css#L93-L100) , if you delete them maybe solve that problem, but maybe appears other issues. jaja

**Comment by sorat0mo** [comment]
Yes, I tested just now and found that disabling `background-color` for `menupopup>menuitem:is([disabled="false"], [selected="true"])` made it normal again. However, the menu item still isn't right.

[Peek 2022-07-08 02-19.webm](https://user-images.githubusercontent.com/11853019/177842502-f4e15c5d-b44a-413c-b5c9-ea53a6ee9216.webm)

Is there any way I can make it same as others?

**Comment by Godiesc** [comment]
Which link are you using to tested? I mean that item is disabled, and that item needs to show with a gray background.

**Comment by Godiesc** [comment]
You could test the latest file of the <code>ogx_contextual-menu.css</code> that I updated before I check your pull request.

**Comment by sorat0mo** [comment]
I will test and open new issue if I notice abnormalities with disabled @media fix.

**Comment by Godiesc** [comment]
Thanks, peace and love. ✌
